package com.caztc.domain;

import java.util.Date;

public class MeetingroomBespeak {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column meetingroom_bespeak.bespeak_id
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	private String bespeakId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column meetingroom_bespeak.meetingroom_id
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	private Integer meetingroomId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column meetingroom_bespeak.user_id
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	private String userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column meetingroom_bespeak.apply_time
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	private Date applyTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column meetingroom_bespeak.meeting_name
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	private String meetingName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column meetingroom_bespeak.strat_time
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	private Date stratTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column meetingroom_bespeak.end_time
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	private Date endTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column meetingroom_bespeak.meetingroom_note
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	private String meetingroomNote;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column meetingroom_bespeak.bespeak_state
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	private String bespeakState;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column meetingroom_bespeak.use_user_id
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	private String useUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column meetingroom_bespeak.auditing_time
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	private Date auditingTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column meetingroom_bespeak.auditing_info
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	private String auditingInfo;

	private String userName;

	private String meetingroomName;

	// 锟斤拷锟斤拷说锟斤拷锟斤拷锟�
	private String useUserName;
	
	private String mark;
	
	

	public String getMark() {
		return mark;
	}

	public void setMark(String mark) {
		this.mark = mark;
	}

	public String getUseUserName() {
		return useUserName;
	}

	public void setUseUserName(String useUserName) {
		this.useUserName = useUserName;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getMeetingroomName() {
		return meetingroomName;
	}

	public void setMeetingroomName(String meetingroomName) {
		this.meetingroomName = meetingroomName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column meetingroom_bespeak.bespeak_id
	 * 
	 * @return the value of meetingroom_bespeak.bespeak_id
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public String getBespeakId() {
		return bespeakId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column meetingroom_bespeak.bespeak_id
	 * 
	 * @param bespeakId
	 *            the value for meetingroom_bespeak.bespeak_id
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public void setBespeakId(String bespeakId) {
		this.bespeakId = bespeakId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column meetingroom_bespeak.meetingroom_id
	 * 
	 * @return the value of meetingroom_bespeak.meetingroom_id
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public Integer getMeetingroomId() {
		return meetingroomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column meetingroom_bespeak.meetingroom_id
	 * 
	 * @param meetingroomId
	 *            the value for meetingroom_bespeak.meetingroom_id
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public void setMeetingroomId(Integer meetingroomId) {
		this.meetingroomId = meetingroomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column meetingroom_bespeak.user_id
	 * 
	 * @return the value of meetingroom_bespeak.user_id
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column meetingroom_bespeak.user_id
	 * 
	 * @param userId
	 *            the value for meetingroom_bespeak.user_id
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column meetingroom_bespeak.apply_time
	 * 
	 * @return the value of meetingroom_bespeak.apply_time
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public Date getApplyTime() {
		return applyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column meetingroom_bespeak.apply_time
	 * 
	 * @param applyTime
	 *            the value for meetingroom_bespeak.apply_time
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column meetingroom_bespeak.meeting_name
	 * 
	 * @return the value of meetingroom_bespeak.meeting_name
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public String getMeetingName() {
		return meetingName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column meetingroom_bespeak.meeting_name
	 * 
	 * @param meetingName
	 *            the value for meetingroom_bespeak.meeting_name
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public void setMeetingName(String meetingName) {
		this.meetingName = meetingName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column meetingroom_bespeak.strat_time
	 * 
	 * @return the value of meetingroom_bespeak.strat_time
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public Date getStratTime() {
		return stratTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column meetingroom_bespeak.strat_time
	 * 
	 * @param stratTime
	 *            the value for meetingroom_bespeak.strat_time
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public void setStratTime(Date stratTime) {
		this.stratTime = stratTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column meetingroom_bespeak.end_time
	 * 
	 * @return the value of meetingroom_bespeak.end_time
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column meetingroom_bespeak.end_time
	 * 
	 * @param endTime
	 *            the value for meetingroom_bespeak.end_time
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column meetingroom_bespeak.meetingroom_note
	 * 
	 * @return the value of meetingroom_bespeak.meetingroom_note
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public String getMeetingroomNote() {
		return meetingroomNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column meetingroom_bespeak.meetingroom_note
	 * 
	 * @param meetingroomNote
	 *            the value for meetingroom_bespeak.meetingroom_note
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public void setMeetingroomNote(String meetingroomNote) {
		this.meetingroomNote = meetingroomNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column meetingroom_bespeak.bespeak_state
	 * 
	 * @return the value of meetingroom_bespeak.bespeak_state
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public String getBespeakState() {
		return bespeakState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column meetingroom_bespeak.bespeak_state
	 * 
	 * @param bespeakState
	 *            the value for meetingroom_bespeak.bespeak_state
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public void setBespeakState(String bespeakState) {
		this.bespeakState = bespeakState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column meetingroom_bespeak.use_user_id
	 * 
	 * @return the value of meetingroom_bespeak.use_user_id
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public String getUseUserId() {
		return useUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column meetingroom_bespeak.use_user_id
	 * 
	 * @param useUserId
	 *            the value for meetingroom_bespeak.use_user_id
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public void setUseUserId(String useUserId) {
		this.useUserId = useUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column meetingroom_bespeak.auditing_time
	 * 
	 * @return the value of meetingroom_bespeak.auditing_time
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public Date getAuditingTime() {
		return auditingTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column meetingroom_bespeak.auditing_time
	 * 
	 * @param auditingTime
	 *            the value for meetingroom_bespeak.auditing_time
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public void setAuditingTime(Date auditingTime) {
		this.auditingTime = auditingTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column meetingroom_bespeak.auditing_info
	 * 
	 * @return the value of meetingroom_bespeak.auditing_info
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public String getAuditingInfo() {
		return auditingInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column meetingroom_bespeak.auditing_info
	 * 
	 * @param auditingInfo
	 *            the value for meetingroom_bespeak.auditing_info
	 * 
	 * @mbggenerated  Wed March 21 13:51:45 CST 2019
	 */
	public void setAuditingInfo(String auditingInfo) {
		this.auditingInfo = auditingInfo;
	}

	@Override
	public String toString() {
		return "MeetingroomBespeak [bespeakId=" + bespeakId
				+ ", meetingroomId=" + meetingroomId + ", userId=" + userId
				+ ", applyTime=" + applyTime + ", meetingName=" + meetingName
				+ ", stratTime=" + stratTime + ", endTime=" + endTime
				+ ", meetingroomNote=" + meetingroomNote + ", bespeakState="
				+ bespeakState + ", useUserId=" + useUserId + ", auditingTime="
				+ auditingTime + ", auditingInfo=" + auditingInfo
				+ ", userName=" + userName + ", meetingroomName="
				+ meetingroomName + "]";
	}


}