package com.caztc.domain;

public class MeetingUserinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_userinfo.meetingroom_user_id
     *
     * @mbggenerated  Wed March 21 13:51:45 CST 2019
     */
    private Integer meetingroomUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_userinfo.user_id
     *
     * @mbggenerated  Wed March 21 13:51:45 CST 2019
     */
    private String userId;
    
    private String userName;
    
    
    private String meetingName;
    
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_userinfo.bespeak_id
     *
     * @mbggenerated  Wed March 21 13:51:45 CST 2019
     */
    private String bespeakId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_userinfo.meetingroom_user_id
     *
     * @return the value of meeting_userinfo.meetingroom_user_id
     *
     * @mbggenerated  Wed March 21 13:51:45 CST 2019
     */
    public Integer getMeetingroomUserId() {
        return meetingroomUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_userinfo.meetingroom_user_id
     *
     * @param meetingroomUserId the value for meeting_userinfo.meetingroom_user_id
     *
     * @mbggenerated  Wed March 21 13:51:45 CST 2019
     */
    public void setMeetingroomUserId(Integer meetingroomUserId) {
        this.meetingroomUserId = meetingroomUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_userinfo.user_id
     *
     * @return the value of meeting_userinfo.user_id
     *
     * @mbggenerated  Wed March 21 13:51:45 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_userinfo.user_id
     *
     * @param userId the value for meeting_userinfo.user_id
     *
     * @mbggenerated  Wed March 21 13:51:45 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_userinfo.bespeak_id
     *
     * @return the value of meeting_userinfo.bespeak_id
     *
     * @mbggenerated  Wed March 21 13:51:45 CST 2019
     */
    public String getBespeakId() {
        return bespeakId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_userinfo.bespeak_id
     *
     * @param bespeakId the value for meeting_userinfo.bespeak_id
     *
     * @mbggenerated  Wed March 21 13:51:45 CST 2019
     */
    public void setBespeakId(String bespeakId) {
        this.bespeakId = bespeakId;
    }

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getMeetingName() {
		return meetingName;
	}

	public void setMeetingName(String meetingName) {
		this.meetingName = meetingName;
	}

	@Override
	public String toString() {
		return "MeetingUserinfo [meetingroomUserId=" + meetingroomUserId
				+ ", userId=" + userId + ", userName=" + userName
				+ ", meetingName=" + meetingName + ", bespeakId=" + bespeakId
				+ "]";
	}
	
	
}